version: '2'
services:
  apollo:
#     image: GMOD/apollo:2.0.2
    image: nathandunn/apollo:2.0.2
#     build: .
    links:
      - db
    ports:
      - "8080:8080"
    environment:
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"
    volumes:
      - "./data:/data"
      - "./apollo:/apollo"
      - "./jbrowse:/jbrowse"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
